-- 0007_local_settings_namespace.sql
-- ЕТАП 6: конвенція неймспейсу ЛОКАЛЬНИХ налаштувань каси
-- (sync-schema-design.md, розділ 8.1: «локальний простір settings.local.*»).
--
-- Таблиця settings (0001) — вже key/value; SQL для неймспейсу не потрібен.
-- Конвенція (валідується застосунком, offline/commands.rs::set_setting):
--   * 'local.*'      — ЛОКАЛЬНІ ключі каси: ніколи не перезаписуються pull
--                      (master-дельта 'settings'), не відправляються на сервер;
--                      приклад: local.last_cashier, local.receipt_printer...
--   * без префікса   — синхронізовані ключі (server_url/api_token/store_id —
--                      конфігурація; інші — pull-настройки сервера, дизайн 5).
--
-- Міграція лише фіксує версію схеми (user_version = 7): DDL відсутній,
-- тому SQL-тіло — коментар-конвенція.
