# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.infrastructure.services.prro import prro_pb2 as prro__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in prro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChkIncomeServiceStub:
    """─── Сервіс ChkIncomeService ─────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendChk = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/sendChk',
                request_serializer=prro__pb2.Check.SerializeToString,
                response_deserializer=prro__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.sendChkV2 = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/sendChkV2',
                request_serializer=prro__pb2.Check.SerializeToString,
                response_deserializer=prro__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.lastChk = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/lastChk',
                request_serializer=prro__pb2.CheckRequest.SerializeToString,
                response_deserializer=prro__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.ping = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/ping',
                request_serializer=prro__pb2.Check.SerializeToString,
                response_deserializer=prro__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.delLastChk = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/delLastChk',
                request_serializer=prro__pb2.CheckRequest.SerializeToString,
                response_deserializer=prro__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.delLastChkId = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/delLastChkId',
                request_serializer=prro__pb2.CheckRequestId.SerializeToString,
                response_deserializer=prro__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.statusRro = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/statusRro',
                request_serializer=prro__pb2.CheckRequest.SerializeToString,
                response_deserializer=prro__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.infoRro = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/infoRro',
                request_serializer=prro__pb2.CheckRequest.SerializeToString,
                response_deserializer=prro__pb2.RroInfoResponse.FromString,
                _registered_method=True)


class ChkIncomeServiceServicer:
    """─── Сервіс ChkIncomeService ─────────────────────────────────────────────────
    """

    def sendChk(self, request, context):
        """Передача чеку / Z-звіту (діє до 01.10.2021)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendChkV2(self, request, context):
        """Передача чеку / Z-звіту (основний метод з 01.10.2021)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def lastChk(self, request, context):
        """Отримання останнього чеку (data_sign містить останній чек)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """Перевірка зв'язку (XML з типом <CT="111">, MAC не заповнюється)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delLastChk(self, request, context):
        """Вилучення останнього чеку (1 раз, тільки чек продажу)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delLastChkId(self, request, context):
        """Вилучення чеку за ID (1 раз, тільки чек продажу)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def statusRro(self, request, context):
        """Отримання статусу ПРРО
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def infoRro(self, request, context):
        """Отримання детальної інформації про ПРРО
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChkIncomeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendChk': grpc.unary_unary_rpc_method_handler(
                    servicer.sendChk,
                    request_deserializer=prro__pb2.Check.FromString,
                    response_serializer=prro__pb2.CheckResponse.SerializeToString,
            ),
            'sendChkV2': grpc.unary_unary_rpc_method_handler(
                    servicer.sendChkV2,
                    request_deserializer=prro__pb2.Check.FromString,
                    response_serializer=prro__pb2.CheckResponse.SerializeToString,
            ),
            'lastChk': grpc.unary_unary_rpc_method_handler(
                    servicer.lastChk,
                    request_deserializer=prro__pb2.CheckRequest.FromString,
                    response_serializer=prro__pb2.CheckResponse.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=prro__pb2.Check.FromString,
                    response_serializer=prro__pb2.CheckResponse.SerializeToString,
            ),
            'delLastChk': grpc.unary_unary_rpc_method_handler(
                    servicer.delLastChk,
                    request_deserializer=prro__pb2.CheckRequest.FromString,
                    response_serializer=prro__pb2.CheckResponse.SerializeToString,
            ),
            'delLastChkId': grpc.unary_unary_rpc_method_handler(
                    servicer.delLastChkId,
                    request_deserializer=prro__pb2.CheckRequestId.FromString,
                    response_serializer=prro__pb2.CheckResponse.SerializeToString,
            ),
            'statusRro': grpc.unary_unary_rpc_method_handler(
                    servicer.statusRro,
                    request_deserializer=prro__pb2.CheckRequest.FromString,
                    response_serializer=prro__pb2.StatusResponse.SerializeToString,
            ),
            'infoRro': grpc.unary_unary_rpc_method_handler(
                    servicer.infoRro,
                    request_deserializer=prro__pb2.CheckRequest.FromString,
                    response_serializer=prro__pb2.RroInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.programika.rro.ws.chk.ChkIncomeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.programika.rro.ws.chk.ChkIncomeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChkIncomeService:
    """─── Сервіс ChkIncomeService ─────────────────────────────────────────────────
    """

    @staticmethod
    def sendChk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/sendChk',
            prro__pb2.Check.SerializeToString,
            prro__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sendChkV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/sendChkV2',
            prro__pb2.Check.SerializeToString,
            prro__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def lastChk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/lastChk',
            prro__pb2.CheckRequest.SerializeToString,
            prro__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/ping',
            prro__pb2.Check.SerializeToString,
            prro__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delLastChk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/delLastChk',
            prro__pb2.CheckRequest.SerializeToString,
            prro__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delLastChkId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/delLastChkId',
            prro__pb2.CheckRequestId.SerializeToString,
            prro__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def statusRro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/statusRro',
            prro__pb2.CheckRequest.SerializeToString,
            prro__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def infoRro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/infoRro',
            prro__pb2.CheckRequest.SerializeToString,
            prro__pb2.RroInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
