"""add original_receipt_id and return_reason to receipts

Revision ID: 1ba90b531d88
Revises: 09288dbfd383
Create Date: 2026-07-29 15:00:02.237698+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba90b531d88'
down_revision: Union[str, None] = '09288dbfd383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('original_receipt_id', sa.UUID(), nullable=True, comment='ID оригінального чеку (для повернень)'))
    op.add_column('receipts', sa.Column('return_reason', sa.String(length=255), nullable=True, comment='Причина повернення'))
    op.create_index(op.f('ix_receipts_original_receipt_id'), 'receipts', ['original_receipt_id'], unique=False)
    op.create_foreign_key(None, 'receipts', 'receipts', ['original_receipt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_original_receipt_id'), table_name='receipts')
    op.drop_column('receipts', 'return_reason')
    op.drop_column('receipts', 'original_receipt_id')
    # ### end Alembic commands ###
