"""add cost_price and markup_percent to invoice_items

Revision ID: 1d972a32ff41
Revises: 7ad557f5e0c8
Create Date: 2026-07-24 21:04:11.002456+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d972a32ff41'
down_revision: Union[str, None] = '7ad557f5e0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Собівартість за одиницю (з ПДВ з накладної)'))
    op.add_column('invoice_items', sa.Column('markup_percent', sa.Numeric(precision=5, scale=1), nullable=True, comment='Відсоток націнки'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'markup_percent')
    op.drop_column('invoice_items', 'cost_price')
    # ### end Alembic commands ###
