"""add_markup_to_product

Revision ID: 22701c46ebe7
Revises: c25cf83669be
Create Date: 2026-07-20 21:57:35.012168+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22701c46ebe7'
down_revision: Union[str, None] = 'c25cf83669be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('barcodes', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор запису штрих-коду',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('barcodes', 'product_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('barcodes', 'barcode',
               existing_type=sa.VARCHAR(length=50),
               comment='Штрих-код (EAN-13, UPC, Code128 тощо)',
               existing_nullable=False)
    op.alter_column('barcodes', 'is_primary',
               existing_type=sa.BOOLEAN(),
               comment='Чи є цей штрих-код основним (для пошуку за замовчуванням)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('barcodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('barcodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор категорії',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Назва категорії',
               existing_nullable=False)
    op.alter_column('categories', 'description',
               existing_type=sa.TEXT(),
               comment='Опис категорії',
               existing_nullable=True)
    op.alter_column('categories', 'parent_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор батьківської категорії (для підкатегорій)',
               existing_nullable=True)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_items', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор накладної',
               existing_nullable=False)
    op.alter_column('invoice_items', 'product_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Кількість товару',
               existing_nullable=False)
    op.alter_column('invoice_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Ціна за одиницю (грн)',
               existing_nullable=False)
    op.alter_column('invoice_items', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Загальна сума позиції (грн)',
               existing_nullable=False)
    op.alter_column('invoice_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор накладної',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('invoices', 'number',
               existing_type=sa.VARCHAR(length=50),
               comment='Номер накладної (внутрішній або від постачальника)',
               existing_nullable=False)
    op.alter_column('invoices', 'supplier_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор постачальника',
               existing_nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата накладної (від постачальника)',
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'confirmed', 'cancelled', name='invoice_status'),
               comment='Статус накладної',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::invoice_status"))
    op.alter_column('invoices', 'notes',
               existing_type=sa.TEXT(),
               comment='Додаткові нотатки до накладної',
               existing_nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Загальна сума накладної (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення запису',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_images', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор зображення',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('product_images', 'product_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('product_images', 'url',
               existing_type=sa.VARCHAR(length=1024),
               comment='URL або шлях до файлу зображення',
               existing_nullable=False)
    op.alter_column('product_images', 'is_main',
               existing_type=sa.BOOLEAN(),
               comment='Чи є це зображення головним (показується в картці товару)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('product_images', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='Порядок сортування (чим менше — тим вище)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('products', sa.Column('markup', sa.Numeric(precision=5, scale=2), nullable=True, comment='Націнка (%)'))
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор товару',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('products', 'barcode',
               existing_type=sa.VARCHAR(length=50),
               comment='Основний штрих-код товару (EAN-13)',
               existing_nullable=True)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=100),
               comment='Артикул товару (внутрішній код)',
               existing_nullable=True)
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Назва товару',
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment='Опис товару',
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Роздрібна ціна (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Собівартість / закупівельна ціна (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('products', 'stock',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Поточний залишок на складі (в одиницях виміру товару)',
               existing_nullable=True,
               existing_server_default=sa.text('0.000'))
    op.alter_column('products', 'uktzed',
               existing_type=sa.VARCHAR(length=10),
               comment='Код УКТЗЕД (для митного оформлення та звітності)',
               existing_nullable=True)
    op.alter_column('products', 'scan_excise',
               existing_type=sa.BOOLEAN(),
               comment='Чи потрібно сканувати акцизну марку при продажу',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Ставка ПДВ (%)',
               existing_nullable=True,
               existing_server_default=sa.text('20.00'))
    op.alter_column('products', 'tax_group',
               existing_type=sa.VARCHAR(length=2),
               comment='Група оподаткування (А, Б, В тощо)',
               existing_nullable=True,
               existing_server_default=sa.text("'А'::character varying"))
    op.alter_column('products', 'is_weight',
               existing_type=sa.BOOLEAN(),
               comment='Чи є товар ваговим (продається за вагою, а не за штуками)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=10),
               comment='Одиниця виміру (шт, кг, л, м тощо)',
               existing_nullable=True,
               existing_server_default=sa.text("'шт'::character varying"))
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор категорії товару',
               existing_nullable=True)
    op.alter_column('products', 'supplier_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор постачальника',
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_products_title_trgm'), table_name='products', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('receipt_items', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('receipt_items', 'receipt_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор чеку',
               existing_nullable=False)
    op.alter_column('receipt_items', 'product_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('receipt_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Кількість товару',
               existing_nullable=False)
    op.alter_column('receipt_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Ціна за одиницю (грн)',
               existing_nullable=False)
    op.alter_column('receipt_items', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Загальна сума позиції (грн)',
               existing_nullable=False)
    op.alter_column('receipt_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('receipts', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор чеку',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('receipts', 'receipt_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Номер чеку (фіскальний або внутрішній)',
               existing_nullable=False)
    op.alter_column('receipts', 'receipt_type',
               existing_type=postgresql.ENUM('sale', 'return', name='receipt_type'),
               comment='Тип чеку: продаж або повернення',
               existing_nullable=False,
               existing_server_default=sa.text("'sale'::receipt_type"))
    op.alter_column('receipts', 'cashier_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор касира, який пробив чек',
               existing_nullable=False)
    op.alter_column('receipts', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Загальна сума чеку (грн)',
               existing_nullable=False)
    op.alter_column('receipts', 'is_return',
               existing_type=sa.BOOLEAN(),
               comment='Чи є цей чек поверненням',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('receipts', 'notes',
               existing_type=sa.TEXT(),
               comment='Додаткові нотатки до чеку',
               existing_nullable=True)
    op.alter_column('receipts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата та час продажу',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('return_invoice_items', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('return_invoice_items', 'return_invoice_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор повернення',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'product_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Кількість товару',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Ціна за одиницю (грн)',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Загальна сума позиції (грн)',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('return_invoices', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор повернення',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('return_invoices', 'number',
               existing_type=sa.VARCHAR(length=50),
               comment='Номер документа повернення',
               existing_nullable=False)
    op.alter_column('return_invoices', 'supplier_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор постачальника',
               existing_nullable=False)
    op.alter_column('return_invoices', 'return_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата повернення',
               existing_nullable=False)
    op.alter_column('return_invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'confirmed', 'cancelled', name='return_invoice_status'),
               comment='Статус повернення',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::return_invoice_status"))
    op.alter_column('return_invoices', 'notes',
               existing_type=sa.TEXT(),
               comment='Причина повернення / додаткові нотатки',
               existing_nullable=True)
    op.alter_column('return_invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Загальна сума повернення (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('return_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('return_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('supplier_ledger', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор запису',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('supplier_ledger', 'supplier_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор постачальника',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'operation_type',
               existing_type=postgresql.ENUM('invoice', 'payment', 'return', 'correction', name='ledger_operation_type'),
               comment='Тип операції',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'document_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор документа (накладної, платежу тощо)',
               existing_nullable=True)
    op.alter_column('supplier_ledger', 'document_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Номер документа',
               existing_nullable=True)
    op.alter_column('supplier_ledger', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Сума операції (грн)',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'balance_after',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Баланс після операції (грн)',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'operation_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата операції',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'notes',
               existing_type=sa.TEXT(),
               comment='Додаткові нотатки',
               existing_nullable=True)
    op.alter_column('supplier_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення запису',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('suppliers', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор постачальника',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Назва постачальника (юр. особа або ФОП)',
               existing_nullable=False)
    op.alter_column('suppliers', 'edrpou',
               existing_type=sa.VARCHAR(length=10),
               comment='Код ЄДРПОУ / ІПН',
               existing_nullable=True)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Номер телефону',
               existing_nullable=True)
    op.alter_column('suppliers', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Електронна пошта',
               existing_nullable=True)
    op.alter_column('suppliers', 'address',
               existing_type=sa.TEXT(),
               comment='Юридична / фактична адреса',
               existing_nullable=True)
    op.alter_column('suppliers', 'notes',
               existing_type=sa.TEXT(),
               comment='Додаткові нотатки',
               existing_nullable=True)
    op.alter_column('suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('suppliers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transfer_items', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('transfer_items', 'transfer_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор переміщення',
               existing_nullable=False)
    op.alter_column('transfer_items', 'product_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('transfer_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Кількість товару',
               existing_nullable=False)
    op.alter_column('transfer_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transfers', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор переміщення',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('transfers', 'number',
               existing_type=sa.VARCHAR(length=50),
               comment='Номер документа переміщення',
               existing_nullable=False)
    op.alter_column('transfers', 'from_location',
               existing_type=sa.VARCHAR(length=255),
               comment='Звідки переміщуємо (склад/магазин)',
               existing_nullable=False)
    op.alter_column('transfers', 'to_location',
               existing_type=sa.VARCHAR(length=255),
               comment='Куди переміщуємо (склад/магазин)',
               existing_nullable=False)
    op.alter_column('transfers', 'transfer_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата переміщення',
               existing_nullable=False)
    op.alter_column('transfers', 'status',
               existing_type=postgresql.ENUM('draft', 'confirmed', 'cancelled', name='transfer_status'),
               comment='Статус переміщення',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::transfer_status"))
    op.alter_column('transfers', 'notes',
               existing_type=sa.TEXT(),
               comment='Додаткові нотатки',
               existing_nullable=True)
    op.alter_column('transfers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transfers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор користувача',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="Повне ім'я користувача",
               existing_nullable=False)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=100),
               comment='Логін для входу в систему',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Хеш пароля (bcrypt)',
               existing_nullable=False)
    op.alter_column('users', 'pin_code',
               existing_type=sa.VARCHAR(length=255),
               comment='Хеш PIN-коду (bcrypt) для швидкої авторизації на касі',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'cashier', name='user_role'),
               comment='Роль користувача: admin або cashier',
               existing_nullable=False,
               existing_server_default=sa.text("'cashier'::user_role"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Чи активний користувач (може входити в систему)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('write_off_items', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('write_off_items', 'write_off_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор списання',
               existing_nullable=False)
    op.alter_column('write_off_items', 'product_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('write_off_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Кількість списаного товару',
               existing_nullable=False)
    op.alter_column('write_off_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('write_offs', 'id',
               existing_type=sa.UUID(),
               comment='Унікальний ідентифікатор списання',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('write_offs', 'number',
               existing_type=sa.VARCHAR(length=50),
               comment='Номер документа списання',
               existing_nullable=False)
    op.alter_column('write_offs', 'reason',
               existing_type=postgresql.ENUM('expired', 'damaged', 'defect', 'theft', 'inventory', 'other', name='write_off_reason'),
               comment='Причина списання',
               existing_nullable=False)
    op.alter_column('write_offs', 'write_off_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата списання',
               existing_nullable=False)
    op.alter_column('write_offs', 'notes',
               existing_type=sa.TEXT(),
               comment='Додаткові нотатки',
               existing_nullable=True)
    op.alter_column('write_offs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('write_offs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('write_offs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('write_offs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('write_offs', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Додаткові нотатки',
               existing_nullable=True)
    op.alter_column('write_offs', 'write_off_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата списання',
               existing_nullable=False)
    op.alter_column('write_offs', 'reason',
               existing_type=postgresql.ENUM('expired', 'damaged', 'defect', 'theft', 'inventory', 'other', name='write_off_reason'),
               comment=None,
               existing_comment='Причина списання',
               existing_nullable=False)
    op.alter_column('write_offs', 'number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Номер документа списання',
               existing_nullable=False)
    op.alter_column('write_offs', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор списання',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('write_off_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('write_off_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment=None,
               existing_comment='Кількість списаного товару',
               existing_nullable=False)
    op.alter_column('write_off_items', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('write_off_items', 'write_off_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор списання',
               existing_nullable=False)
    op.alter_column('write_off_items', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Чи активний користувач (може входити в систему)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'cashier', name='user_role'),
               comment=None,
               existing_comment='Роль користувача: admin або cashier',
               existing_nullable=False,
               existing_server_default=sa.text("'cashier'::user_role"))
    op.alter_column('users', 'pin_code',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Хеш PIN-коду (bcrypt) для швидкої авторизації на касі',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Хеш пароля (bcrypt)',
               existing_nullable=False)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Логін для входу в систему',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Повне ім'я користувача",
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор користувача',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('transfers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transfers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transfers', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Додаткові нотатки',
               existing_nullable=True)
    op.alter_column('transfers', 'status',
               existing_type=postgresql.ENUM('draft', 'confirmed', 'cancelled', name='transfer_status'),
               comment=None,
               existing_comment='Статус переміщення',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::transfer_status"))
    op.alter_column('transfers', 'transfer_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата переміщення',
               existing_nullable=False)
    op.alter_column('transfers', 'to_location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Куди переміщуємо (склад/магазин)',
               existing_nullable=False)
    op.alter_column('transfers', 'from_location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Звідки переміщуємо (склад/магазин)',
               existing_nullable=False)
    op.alter_column('transfers', 'number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Номер документа переміщення',
               existing_nullable=False)
    op.alter_column('transfers', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор переміщення',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('transfer_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transfer_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment=None,
               existing_comment='Кількість товару',
               existing_nullable=False)
    op.alter_column('transfer_items', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('transfer_items', 'transfer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор переміщення',
               existing_nullable=False)
    op.alter_column('transfer_items', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('suppliers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('suppliers', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Додаткові нотатки',
               existing_nullable=True)
    op.alter_column('suppliers', 'address',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Юридична / фактична адреса',
               existing_nullable=True)
    op.alter_column('suppliers', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Електронна пошта',
               existing_nullable=True)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Номер телефону',
               existing_nullable=True)
    op.alter_column('suppliers', 'edrpou',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Код ЄДРПОУ / ІПН',
               existing_nullable=True)
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Назва постачальника (юр. особа або ФОП)',
               existing_nullable=False)
    op.alter_column('suppliers', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор постачальника',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('supplier_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення запису',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('supplier_ledger', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Додаткові нотатки',
               existing_nullable=True)
    op.alter_column('supplier_ledger', 'operation_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата операції',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'balance_after',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Баланс після операції (грн)',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Сума операції (грн)',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'document_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Номер документа',
               existing_nullable=True)
    op.alter_column('supplier_ledger', 'document_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор документа (накладної, платежу тощо)',
               existing_nullable=True)
    op.alter_column('supplier_ledger', 'operation_type',
               existing_type=postgresql.ENUM('invoice', 'payment', 'return', 'correction', name='ledger_operation_type'),
               comment=None,
               existing_comment='Тип операції',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'supplier_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор постачальника',
               existing_nullable=False)
    op.alter_column('supplier_ledger', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор запису',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('return_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('return_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('return_invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Загальна сума повернення (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('return_invoices', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Причина повернення / додаткові нотатки',
               existing_nullable=True)
    op.alter_column('return_invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'confirmed', 'cancelled', name='return_invoice_status'),
               comment=None,
               existing_comment='Статус повернення',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::return_invoice_status"))
    op.alter_column('return_invoices', 'return_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата повернення',
               existing_nullable=False)
    op.alter_column('return_invoices', 'supplier_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор постачальника',
               existing_nullable=False)
    op.alter_column('return_invoices', 'number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Номер документа повернення',
               existing_nullable=False)
    op.alter_column('return_invoices', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор повернення',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('return_invoice_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('return_invoice_items', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Загальна сума позиції (грн)',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Ціна за одиницю (грн)',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment=None,
               existing_comment='Кількість товару',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'return_invoice_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор повернення',
               existing_nullable=False)
    op.alter_column('return_invoice_items', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('receipts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата та час продажу',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('receipts', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Додаткові нотатки до чеку',
               existing_nullable=True)
    op.alter_column('receipts', 'is_return',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Чи є цей чек поверненням',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('receipts', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Загальна сума чеку (грн)',
               existing_nullable=False)
    op.alter_column('receipts', 'cashier_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор касира, який пробив чек',
               existing_nullable=False)
    op.alter_column('receipts', 'receipt_type',
               existing_type=postgresql.ENUM('sale', 'return', name='receipt_type'),
               comment=None,
               existing_comment='Тип чеку: продаж або повернення',
               existing_nullable=False,
               existing_server_default=sa.text("'sale'::receipt_type"))
    op.alter_column('receipts', 'receipt_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Номер чеку (фіскальний або внутрішній)',
               existing_nullable=False)
    op.alter_column('receipts', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор чеку',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('receipt_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('receipt_items', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Загальна сума позиції (грн)',
               existing_nullable=False)
    op.alter_column('receipt_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Ціна за одиницю (грн)',
               existing_nullable=False)
    op.alter_column('receipt_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment=None,
               existing_comment='Кількість товару',
               existing_nullable=False)
    op.alter_column('receipt_items', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('receipt_items', 'receipt_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор чеку',
               existing_nullable=False)
    op.alter_column('receipt_items', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.create_index(op.f('ix_products_title_trgm'), 'products', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'supplier_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор постачальника',
               existing_nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор категорії товару',
               existing_nullable=True)
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Одиниця виміру (шт, кг, л, м тощо)',
               existing_nullable=True,
               existing_server_default=sa.text("'шт'::character varying"))
    op.alter_column('products', 'is_weight',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Чи є товар ваговим (продається за вагою, а не за штуками)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tax_group',
               existing_type=sa.VARCHAR(length=2),
               comment=None,
               existing_comment='Група оподаткування (А, Б, В тощо)',
               existing_nullable=True,
               existing_server_default=sa.text("'А'::character varying"))
    op.alter_column('products', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Ставка ПДВ (%)',
               existing_nullable=True,
               existing_server_default=sa.text('20.00'))
    op.alter_column('products', 'scan_excise',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Чи потрібно сканувати акцизну марку при продажу',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'uktzed',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Код УКТЗЕД (для митного оформлення та звітності)',
               existing_nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment=None,
               existing_comment='Поточний залишок на складі (в одиницях виміру товару)',
               existing_nullable=True,
               existing_server_default=sa.text('0.000'))
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Собівартість / закупівельна ціна (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Роздрібна ціна (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Опис товару',
               existing_nullable=True)
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Назва товару',
               existing_nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Артикул товару (внутрішній код)',
               existing_nullable=True)
    op.alter_column('products', 'barcode',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Основний штрих-код товару (EAN-13)',
               existing_nullable=True)
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор товару',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('products', 'markup')
    op.alter_column('product_images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_images', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Порядок сортування (чим менше — тим вище)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_images', 'is_main',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Чи є це зображення головним (показується в картці товару)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('product_images', 'url',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='URL або шлях до файлу зображення',
               existing_nullable=False)
    op.alter_column('product_images', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('product_images', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор зображення',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення запису',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Загальна сума накладної (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoices', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Додаткові нотатки до накладної',
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'confirmed', 'cancelled', name='invoice_status'),
               comment=None,
               existing_comment='Статус накладної',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::invoice_status"))
    op.alter_column('invoices', 'invoice_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата накладної (від постачальника)',
               existing_nullable=False)
    op.alter_column('invoices', 'supplier_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор постачальника',
               existing_nullable=False)
    op.alter_column('invoices', 'number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Номер накладної (внутрішній або від постачальника)',
               existing_nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор накладної',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('invoice_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_items', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Загальна сума позиції (грн)',
               existing_nullable=False)
    op.alter_column('invoice_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Ціна за одиницю (грн)',
               existing_nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment=None,
               existing_comment='Кількість товару',
               existing_nullable=False)
    op.alter_column('invoice_items', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор накладної',
               existing_nullable=False)
    op.alter_column('invoice_items', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор позиції',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'parent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор батьківської категорії (для підкатегорій)',
               existing_nullable=True)
    op.alter_column('categories', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Опис категорії',
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Назва категорії',
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор категорії',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('barcodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата останнього оновлення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('barcodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата створення',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('barcodes', 'is_primary',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Чи є цей штрих-код основним (для пошуку за замовчуванням)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('barcodes', 'barcode',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Штрих-код (EAN-13, UPC, Code128 тощо)',
               existing_nullable=False)
    op.alter_column('barcodes', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ідентифікатор товару',
               existing_nullable=False)
    op.alter_column('barcodes', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Унікальний ідентифікатор запису штрих-коду',
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    # ### end Alembic commands ###
