"""add price_without_vat to products

Revision ID: 2478c1e397a8
Revises: c514eca392be
Create Date: 2026-07-20 23:06:13.634036+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2478c1e397a8'
down_revision: Union[str, None] = 'c514eca392be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_without_vat', sa.Numeric(precision=10, scale=2), nullable=True, comment='Ціна без ПДВ (грн)'))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Роздрібна ціна з ПДВ (грн)',
               existing_comment='Роздрібна ціна (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Роздрібна ціна (грн)',
               existing_comment='Роздрібна ціна з ПДВ (грн)',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_column('products', 'price_without_vat')
    # ### end Alembic commands ###
