"""add recommended_qty to products

Revision ID: 29a1b933fda9
Revises: feee035d65e9
Create Date: 2026-07-24 23:49:40.497937+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a1b933fda9'
down_revision: Union[str, None] = 'feee035d65e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('recommended_qty', sa.Numeric(precision=10, scale=3), nullable=True, comment='Рекомендована кількість (мінімальний залишок для замовлення)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'recommended_qty')
    # ### end Alembic commands ###
