"""add_cost_price_markup_to_return_items

Revision ID: 51984f732fda
Revises: ecad1d30fec1
Create Date: 2026-07-25 17:29:27.442651+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51984f732fda'
down_revision: Union[str, None] = 'ecad1d30fec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_invoice_items', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Собівартість одиниці товару на момент повернення (грн)'))
    op.add_column('return_invoice_items', sa.Column('markup_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Відсоток націнки товару на момент повернення'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_invoice_items', 'markup_percent')
    op.drop_column('return_invoice_items', 'cost_price')
    # ### end Alembic commands ###
