"""add_previous_price_to_invoice_items

Revision ID: 56b4c1696966
Revises: 1ba90b531d88
Create Date: 2026-07-30 21:34:56.938946+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56b4c1696966'
down_revision: Union[str, None] = '1ba90b531d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('previous_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Ціна товару до створення накладної (для відстеження змін)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'previous_price')
    # ### end Alembic commands ###
