"""Створення всіх таблиць

Revision ID: 62c0fd0b93a4
Revises: 0001
Create Date: 2026-07-20 14:50:13.508879+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c0fd0b93a4'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор категорії'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Назва категорії'),
    sa.Column('description', sa.Text(), nullable=True, comment='Опис категорії'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Ідентифікатор батьківської категорії (для підкатегорій)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор постачальника'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Назва постачальника (юр. особа або ФОП)'),
    sa.Column('edrpou', sa.String(length=10), nullable=True, comment='Код ЄДРПОУ / ІПН'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Номер телефону'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Електронна пошта'),
    sa.Column('address', sa.Text(), nullable=True, comment='Юридична / фактична адреса'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Додаткові нотатки'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор переміщення'),
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер документа переміщення'),
    sa.Column('from_location', sa.String(length=255), nullable=False, comment='Звідки переміщуємо (склад/магазин)'),
    sa.Column('to_location', sa.String(length=255), nullable=False, comment='Куди переміщуємо (склад/магазин)'),
    sa.Column('transfer_date', sa.DateTime(), nullable=False, comment='Дата переміщення'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'CANCELLED', name='transfer_status', create_constraint=True), nullable=False, comment='Статус переміщення'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Додаткові нотатки'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_number'), 'transfers', ['number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор користувача'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Повне ім'я користувача"),
    sa.Column('login', sa.String(length=100), nullable=False, comment='Логін для входу в систему'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Хеш пароля (bcrypt)'),
    sa.Column('pin_code', sa.String(length=255), nullable=True, comment='Хеш PIN-коду (bcrypt) для швидкої авторизації на касі'),
    sa.Column('role', sa.Enum('admin', 'cashier', name='user_role', create_constraint=True), nullable=False, comment='Роль користувача: admin або cashier'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Чи активний користувач (може входити в систему)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('write_offs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор списання'),
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер документа списання'),
    sa.Column('reason', sa.Enum('EXPIRED', 'DAMAGED', 'DEFECT', 'THEFT', 'INVENTORY', 'OTHER', name='write_off_reason', create_constraint=True), nullable=False, comment='Причина списання'),
    sa.Column('write_off_date', sa.DateTime(), nullable=False, comment='Дата списання'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Додаткові нотатки'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_write_offs_number'), 'write_offs', ['number'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор накладної'),
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер накладної (внутрішній або від постачальника)'),
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='Ідентифікатор постачальника'),
    sa.Column('invoice_date', sa.DateTime(), nullable=False, comment='Дата накладної (від постачальника)'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'CANCELLED', name='invoice_status', create_constraint=True), nullable=False, comment='Статус накладної'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Додаткові нотатки до накладної'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Загальна сума накладної (грн)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення запису'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор товару'),
    sa.Column('barcode', sa.String(length=50), nullable=True, comment='Основний штрих-код товару (EAN-13)'),
    sa.Column('sku', sa.String(length=100), nullable=True, comment='Артикул товару (внутрішній код)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Назва товару'),
    sa.Column('description', sa.Text(), nullable=True, comment='Опис товару'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Роздрібна ціна (грн)'),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Собівартість / закупівельна ціна (грн)'),
    sa.Column('stock', sa.Numeric(precision=10, scale=3), nullable=True, comment='Поточний залишок на складі (в одиницях виміру товару)'),
    sa.Column('uktzed', sa.String(length=10), nullable=True, comment='Код УКТЗЕД (для митного оформлення та звітності)'),
    sa.Column('scan_excise', sa.Boolean(), nullable=False, comment='Чи потрібно сканувати акцизну марку при продажу'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Ставка ПДВ (%)'),
    sa.Column('tax_group', sa.String(length=2), nullable=True, comment='Група оподаткування (А, Б, В тощо)'),
    sa.Column('is_weight', sa.Boolean(), nullable=False, comment='Чи є товар ваговим (продається за вагою, а не за штуками)'),
    sa.Column('unit', sa.String(length=10), nullable=True, comment='Одиниця виміру (шт, кг, л, м тощо)'),
    sa.Column('category_id', sa.UUID(), nullable=True, comment='Ідентифікатор категорії товару'),
    sa.Column('supplier_id', sa.UUID(), nullable=True, comment='Ідентифікатор постачальника'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор чеку'),
    sa.Column('receipt_number', sa.String(length=50), nullable=False, comment='Номер чеку (фіскальний або внутрішній)'),
    sa.Column('receipt_type', sa.Enum('SALE', 'RETURN', name='receipt_type', create_constraint=True), nullable=False, comment='Тип чеку: продаж або повернення'),
    sa.Column('cashier_id', sa.UUID(), nullable=False, comment='Ідентифікатор касира, який пробив чек'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Загальна сума чеку (грн)'),
    sa.Column('is_return', sa.Boolean(), nullable=False, comment='Чи є цей чек поверненням'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Додаткові нотатки до чеку'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата та час продажу'),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_cashier_id'), 'receipts', ['cashier_id'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=False)
    op.create_table('return_invoices',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор повернення'),
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер документа повернення'),
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='Ідентифікатор постачальника'),
    sa.Column('return_date', sa.DateTime(), nullable=False, comment='Дата повернення'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'CANCELLED', name='return_invoice_status', create_constraint=True), nullable=False, comment='Статус повернення'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Причина повернення / додаткові нотатки'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Загальна сума повернення (грн)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_invoices_number'), 'return_invoices', ['number'], unique=False)
    op.create_index(op.f('ix_return_invoices_supplier_id'), 'return_invoices', ['supplier_id'], unique=False)
    op.create_table('supplier_ledger',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор запису'),
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='Ідентифікатор постачальника'),
    sa.Column('operation_type', sa.Enum('INVOICE', 'PAYMENT', 'RETURN', 'CORRECTION', name='ledger_operation_type', create_constraint=True), nullable=False, comment='Тип операції'),
    sa.Column('document_id', sa.UUID(), nullable=True, comment='Ідентифікатор документа (накладної, платежу тощо)'),
    sa.Column('document_number', sa.String(length=50), nullable=True, comment='Номер документа'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Сума операції (грн)'),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False, comment='Баланс після операції (грн)'),
    sa.Column('operation_date', sa.DateTime(), nullable=False, comment='Дата операції'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Додаткові нотатки'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення запису'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_ledger_supplier_id'), 'supplier_ledger', ['supplier_id'], unique=False)
    op.create_table('barcodes',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор запису штрих-коду'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Ідентифікатор товару'),
    sa.Column('barcode', sa.String(length=50), nullable=False, comment='Штрих-код (EAN-13, UPC, Code128 тощо)'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Чи є цей штрих-код основним (для пошуку за замовчуванням)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcodes_barcode'), 'barcodes', ['barcode'], unique=True)
    op.create_index(op.f('ix_barcodes_product_id'), 'barcodes', ['product_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор позиції'),
    sa.Column('invoice_id', sa.UUID(), nullable=False, comment='Ідентифікатор накладної'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Ідентифікатор товару'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Кількість товару'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Ціна за одиницю (грн)'),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False, comment='Загальна сума позиції (грн)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_product_id'), 'invoice_items', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор зображення'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Ідентифікатор товару'),
    sa.Column('url', sa.String(length=1024), nullable=False, comment='URL або шлях до файлу зображення'),
    sa.Column('is_main', sa.Boolean(), nullable=False, comment='Чи є це зображення головним (показується в картці товару)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Порядок сортування (чим менше — тим вище)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('receipt_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор позиції'),
    sa.Column('receipt_id', sa.UUID(), nullable=False, comment='Ідентифікатор чеку'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Ідентифікатор товару'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Кількість товару'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Ціна за одиницю (грн)'),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False, comment='Загальна сума позиції (грн)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_product_id'), 'receipt_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_receipt_items_receipt_id'), 'receipt_items', ['receipt_id'], unique=False)
    op.create_table('return_invoice_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор позиції'),
    sa.Column('return_invoice_id', sa.UUID(), nullable=False, comment='Ідентифікатор повернення'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Ідентифікатор товару'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Кількість товару'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Ціна за одиницю (грн)'),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False, comment='Загальна сума позиції (грн)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_invoice_id'], ['return_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_invoice_items_product_id'), 'return_invoice_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_return_invoice_items_return_invoice_id'), 'return_invoice_items', ['return_invoice_id'], unique=False)
    op.create_table('transfer_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор позиції'),
    sa.Column('transfer_id', sa.UUID(), nullable=False, comment='Ідентифікатор переміщення'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Ідентифікатор товару'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Кількість товару'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_items_product_id'), 'transfer_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_transfer_items_transfer_id'), 'transfer_items', ['transfer_id'], unique=False)
    op.create_table('write_off_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор позиції'),
    sa.Column('write_off_id', sa.UUID(), nullable=False, comment='Ідентифікатор списання'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Ідентифікатор товару'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Кількість списаного товару'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['write_off_id'], ['write_offs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_write_off_items_product_id'), 'write_off_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_write_off_items_write_off_id'), 'write_off_items', ['write_off_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_write_off_items_write_off_id'), table_name='write_off_items')
    op.drop_index(op.f('ix_write_off_items_product_id'), table_name='write_off_items')
    op.drop_table('write_off_items')
    op.drop_index(op.f('ix_transfer_items_transfer_id'), table_name='transfer_items')
    op.drop_index(op.f('ix_transfer_items_product_id'), table_name='transfer_items')
    op.drop_table('transfer_items')
    op.drop_index(op.f('ix_return_invoice_items_return_invoice_id'), table_name='return_invoice_items')
    op.drop_index(op.f('ix_return_invoice_items_product_id'), table_name='return_invoice_items')
    op.drop_table('return_invoice_items')
    op.drop_index(op.f('ix_receipt_items_receipt_id'), table_name='receipt_items')
    op.drop_index(op.f('ix_receipt_items_product_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_invoice_items_product_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_barcodes_product_id'), table_name='barcodes')
    op.drop_index(op.f('ix_barcodes_barcode'), table_name='barcodes')
    op.drop_table('barcodes')
    op.drop_index(op.f('ix_supplier_ledger_supplier_id'), table_name='supplier_ledger')
    op.drop_table('supplier_ledger')
    op.drop_index(op.f('ix_return_invoices_supplier_id'), table_name='return_invoices')
    op.drop_index(op.f('ix_return_invoices_number'), table_name='return_invoices')
    op.drop_table('return_invoices')
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_cashier_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_write_offs_number'), table_name='write_offs')
    op.drop_table('write_offs')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transfers_number'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
