"""add_debtor_payments_table

Revision ID: 7ad557f5e0c8
Revises: 86e9449c9937
Create Date: 2026-07-22 17:00:32.177017+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad557f5e0c8'
down_revision: Union[str, None] = '86e9449c9937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debtor_payments',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор оплати'),
    sa.Column('debtor_id', sa.UUID(), nullable=False, comment='ID боржника'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Сума оплати'),
    sa.Column('payment_method', sa.String(length=20), nullable=True, comment='Спосіб оплати: cash, card, transfer, mixed'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата оплати'),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debtor_payments_debtor_id'), 'debtor_payments', ['debtor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debtor_payments_debtor_id'), table_name='debtor_payments')
    op.drop_table('debtor_payments')
    # ### end Alembic commands ###
