"""add_permissions_field_to_users

Revision ID: 7f7208ec9b81
Revises: b2cff23d7bea
Create Date: 2026-07-21 13:33:29.645819+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f7208ec9b81'
down_revision: Union[str, None] = 'b2cff23d7bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Список прав доступу (масив рядків-пермішенів). Якщо None — використовуються права за замовчуванням для ролі.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
