"""add cost_price and price to inventory_items

Revision ID: 821a55b8067a
Revises: 1d972a32ff41
Create Date: 2026-07-24 22:21:44.457204+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821a55b8067a'
down_revision: Union[str, None] = '1d972a32ff41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор інвентаризації'),
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер документа інвентаризації (префікс ІН-)'),
    sa.Column('location', sa.String(length=255), nullable=False, comment='Локація проведення (магазин/склад)'),
    sa.Column('inventory_date', sa.DateTime(), nullable=False, comment='Дата проведення інвентаризації'),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'cancelled', name='inventory_status', create_constraint=True), nullable=False, comment='Статус інвентаризації'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Додаткові нотатки'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventories_number'), 'inventories', ['number'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор позиції'),
    sa.Column('inventory_id', sa.UUID(), nullable=False, comment='Ідентифікатор інвентаризації'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Ідентифікатор товару'),
    sa.Column('actual_quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Фактична кількість (введена користувачем)'),
    sa.Column('accounting_quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Облікова кількість (поточний залишок)'),
    sa.Column('difference', sa.Numeric(precision=10, scale=3), nullable=False, comment='Різниця = actual - accounting'),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Собівартість одиниці товару на момент інвентаризації'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Ціна продажу одиниці товару на момент інвентаризації'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_inventory_id'), 'inventory_items', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_product_id'), 'inventory_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_product_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_inventory_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_inventories_number'), table_name='inventories')
    op.drop_table('inventories')
    # ### end Alembic commands ###
