"""add_purchase_orders

Revision ID: 86e9449c9937
Revises: e11b26aed987
Create Date: 2026-07-21 23:03:45.677653+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e9449c9937'
down_revision: Union[str, None] = 'e11b26aed987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор замовлення'),
    sa.Column('number', sa.String(length=50), nullable=False, comment='Номер замовлення'),
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='Ідентифікатор постачальника'),
    sa.Column('order_date', sa.DateTime(), nullable=False, comment='Дата замовлення'),
    sa.Column('expected_date', sa.DateTime(), nullable=True, comment='Очікувана дата поставки'),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'cancelled', name='purchase_order_status', create_constraint=True), nullable=False, comment='Статус замовлення'),
    sa.Column('is_fiscal', sa.Boolean(), nullable=False, comment='Фіскальний документ'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Додаткові нотатки до замовлення'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Загальна сума замовлення (грн)'),
    sa.Column('invoice_id', sa.UUID(), nullable=True, comment='ID прибуткової накладної, створеної при підтвердженні замовлення'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_invoice_id'), 'purchase_orders', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_number'), 'purchase_orders', ['number'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор позиції'),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False, comment='Ідентифікатор замовлення'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Ідентифікатор товару'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False, comment='Замовлена кількість'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Ціна за одиницю (грн)'),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False, comment='Загальна сума позиції (грн)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_invoice_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
