"""add_paid_amount_and_debtor_id_to_receipts

Revision ID: b2cff23d7bea
Revises: fc3ebf74b71b
Create Date: 2026-07-21 13:04:48.602298+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2cff23d7bea'
down_revision: Union[str, None] = 'fc3ebf74b71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Фактично сплачена сума (грн). Якщо менша за total_amount — різниця в борг'))
    op.add_column('receipts', sa.Column('debtor_id', sa.UUID(), nullable=True, comment='ID боржника (якщо покупка в борг)'))
    op.create_index(op.f('ix_receipts_debtor_id'), 'receipts', ['debtor_id'], unique=False)
    op.create_foreign_key(None, 'receipts', 'debtors', ['debtor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_debtor_id'), table_name='receipts')
    op.drop_column('receipts', 'debtor_id')
    op.drop_column('receipts', 'paid_amount')
    # ### end Alembic commands ###
