"""add_purchase_price_to_receipt_items

Revision ID: c514eca392be
Revises: 22701c46ebe7
Create Date: 2026-07-20 22:32:08.624047+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c514eca392be'
down_revision: Union[str, None] = '22701c46ebe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Собівартість товару на момент продажу (грн)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_items', 'purchase_price')
    # ### end Alembic commands ###
