"""add work sessions and hourly rate

Revision ID: d08dc43dd496
Revises: e3186c88fc28
Create Date: 2026-07-25 22:26:24.201423+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08dc43dd496'
down_revision: Union[str, None] = 'e3186c88fc28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор робочої сесії'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Ідентифікатор користувача (касира)'),
    sa.Column('login_time', sa.DateTime(), nullable=False, comment='Час входу (початок зміни)'),
    sa.Column('logout_time', sa.DateTime(), nullable=True, comment='Час виходу (завершення зміни). Якщо None — сесія активна'),
    sa.Column('duration_hours', sa.Numeric(precision=5, scale=2), nullable=True, comment='Тривалість сесії в годинах (розраховується при logout)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення запису'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_sessions_user_id'), 'work_sessions', ['user_id'], unique=False)
    op.alter_column('inventories', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив інвентаризацію',
               existing_comment='Ідентифікатор користувача, який створив документ',
               existing_nullable=False)
    op.alter_column('invoices', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив накладну',
               existing_comment='Ідентифікатор користувача, який створив документ',
               existing_nullable=False)
    op.alter_column('purchase_orders', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив замовлення',
               existing_comment='Ідентифікатор користувача, який створив документ',
               existing_nullable=False)
    op.alter_column('return_invoices', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив повернення',
               existing_comment='Ідентифікатор користувача, який створив документ',
               existing_nullable=False)
    op.alter_column('transfers', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив переміщення',
               existing_comment='Ідентифікатор користувача, який створив документ',
               existing_nullable=False)
    op.add_column('users', sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='Ставка за годину роботи (грн). Використовується для розрахунку зарплати'))
    op.alter_column('write_offs', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив списання',
               existing_comment='Ідентифікатор користувача, який створив документ',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('write_offs', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив документ',
               existing_comment='Ідентифікатор користувача, який створив списання',
               existing_nullable=False)
    op.drop_column('users', 'hourly_rate')
    op.alter_column('transfers', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив документ',
               existing_comment='Ідентифікатор користувача, який створив переміщення',
               existing_nullable=False)
    op.alter_column('return_invoices', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив документ',
               existing_comment='Ідентифікатор користувача, який створив повернення',
               existing_nullable=False)
    op.alter_column('purchase_orders', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив документ',
               existing_comment='Ідентифікатор користувача, який створив замовлення',
               existing_nullable=False)
    op.alter_column('invoices', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив документ',
               existing_comment='Ідентифікатор користувача, який створив накладну',
               existing_nullable=False)
    op.alter_column('inventories', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Ідентифікатор користувача, який створив документ',
               existing_comment='Ідентифікатор користувача, який створив інвентаризацію',
               existing_nullable=False)
    op.drop_index(op.f('ix_work_sessions_user_id'), table_name='work_sessions')
    op.drop_table('work_sessions')
    # ### end Alembic commands ###
