"""add_exchange_invoice_id_to_return_invoices

Revision ID: e11b26aed987
Revises: fa9576738a3a
Create Date: 2026-07-21 22:56:13.868856+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11b26aed987'
down_revision: Union[str, None] = 'fa9576738a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_invoices', sa.Column('exchange_invoice_id', sa.UUID(), nullable=True, comment='ID прибуткової накладної, створеної при обміні на інший товар'))
    op.create_index(op.f('ix_return_invoices_exchange_invoice_id'), 'return_invoices', ['exchange_invoice_id'], unique=False)
    op.create_foreign_key(None, 'return_invoices', 'invoices', ['exchange_invoice_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'return_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_return_invoices_exchange_invoice_id'), table_name='return_invoices')
    op.drop_column('return_invoices', 'exchange_invoice_id')
    # ### end Alembic commands ###
