"""add_source_invoice_id_to_return_invoices

Revision ID: ecad1d30fec1
Revises: fe6ecb335509
Create Date: 2026-07-25 17:21:38.740077+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecad1d30fec1'
down_revision: Union[str, None] = 'fe6ecb335509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_invoices', sa.Column('source_invoice_id', sa.UUID(), nullable=True, comment='ID прибуткової накладної, до якої відноситься повернення (опціонально)'))
    op.create_index(op.f('ix_return_invoices_source_invoice_id'), 'return_invoices', ['source_invoice_id'], unique=False)
    op.create_foreign_key(None, 'return_invoices', 'invoices', ['source_invoice_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'return_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_return_invoices_source_invoice_id'), table_name='return_invoices')
    op.drop_column('return_invoices', 'source_invoice_id')
    # ### end Alembic commands ###
