"""add system_settings table

Revision ID: f89706f0cc12
Revises: 51984f732fda
Create Date: 2026-07-25 19:17:11.174503+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89706f0cc12'
down_revision: Union[str, None] = '51984f732fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор налаштування'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='Модуль: general, pos, printing, pricing, notifications, integrations, security, backup'),
    sa.Column('key', sa.String(length=100), nullable=False, comment="Унікальний ключ налаштування, наприклад 'company_name'"),
    sa.Column('value', sa.Text(), nullable=True, comment='Значення налаштування (зберігається як текст)'),
    sa.Column('value_type', sa.String(length=20), nullable=False, comment='Тип значення: string, boolean, number, select'),
    sa.Column('label', sa.String(length=255), nullable=False, comment='Людино-зрозуміла назва налаштування (укр.)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Опис налаштування'),
    sa.Column('options', sa.Text(), nullable=True, comment='JSON-список варіантів для select, напр. \'["1","10","50"]\''),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Чи активне налаштування'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата останнього оновлення'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_index(op.f('ix_system_settings_module'), 'system_settings', ['module'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_module'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
