"""add_debtors_table

Revision ID: fc3ebf74b71b
Revises: 1eb459daa75e
Create Date: 2026-07-21 12:33:51.071482+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3ebf74b71b'
down_revision: Union[str, None] = '1eb459daa75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debtors',
    sa.Column('id', sa.UUID(), nullable=False, comment='Унікальний ідентифікатор боржника'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Повне ім'я боржника"),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Номер телефону'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Додаткові нотатки'),
    sa.Column('total_debt', sa.Numeric(precision=12, scale=2), nullable=False, comment='Загальна сума боргу'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата створення'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата останнього оновлення'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debtors_name'), 'debtors', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debtors_name'), table_name='debtors')
    op.drop_table('debtors')
    # ### end Alembic commands ###
