"""add_change_amount_to_receipts

Revision ID: fe6ecb335509
Revises: 29a1b933fda9
Create Date: 2026-07-25 00:58:02.434476+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6ecb335509'
down_revision: Union[str, None] = '29a1b933fda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'recommended_qty',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Рекомендований залишок (мінімальний залишок для замовлення)',
               existing_comment='Рекомендована кількість (мінімальний залишок для замовлення)',
               existing_nullable=True)
    op.add_column('receipts', sa.Column('change_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Сума здачі (грн). Якщо paid_amount > total_amount'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'change_amount')
    op.alter_column('products', 'recommended_qty',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Рекомендована кількість (мінімальний залишок для замовлення)',
               existing_comment='Рекомендований залишок (мінімальний залишок для замовлення)',
               existing_nullable=True)
    # ### end Alembic commands ###
