"""make location nullable in inventories

Revision ID: feee035d65e9
Revises: 821a55b8067a
Create Date: 2026-07-24 22:52:24.124875+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feee035d65e9'
down_revision: Union[str, None] = '821a55b8067a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Застосувати міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventories', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Локація проведення (магазин/склад)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Відкотити міграцію."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventories', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Локація проведення (магазин/склад)')
    # ### end Alembic commands ###
