-- Точна форма майбутнього запиту: total як скалярний підзапит + пошук через IN(UNION trgm).
SET plan_cache_mode = force_generic_plan;
\echo === C2: каталог+пошук, IN(UNION), total скалярним підзапитом ===
EXPLAIN (ANALYZE, TIMING OFF) SELECT p.id, p.barcode, p.sku, p.title, p.description, COALESCE(NULLIF(st.price,0),p.price)::text AS price, p.cost_price::text, p.markup::text, COALESCE(st.quantity,p.stock)::text AS stock, p.recommended_qty::text, p.uktzed, p.scan_excise, p.tax_rate::text, p.tax_group, p.is_weight, p.unit, p.category_id, p.supplier_id, p.created_at, p.updated_at, (SELECT count(*) FROM products p LEFT JOIN stock st ON st.product_id = p.id AND st.store_id = '65d5db51-672f-4a38-9c1e-f36c5feb5374'::uuid WHERE p.id IN (SELECT id FROM products WHERE title ILIKE '%молоко%' UNION SELECT id FROM products WHERE barcode ILIKE '%молоко%' UNION SELECT id FROM products WHERE sku ILIKE '%молоко%' UNION SELECT product_id FROM barcodes WHERE barcode ILIKE '%молоко%')) AS total_count FROM products p LEFT JOIN stock st ON st.product_id = p.id AND st.store_id = '65d5db51-672f-4a38-9c1e-f36c5feb5374'::uuid WHERE p.id IN (SELECT id FROM products WHERE title ILIKE '%молоко%' UNION SELECT id FROM products WHERE barcode ILIKE '%молоко%' UNION SELECT id FROM products WHERE sku ILIKE '%молоко%' UNION SELECT product_id FROM barcodes WHERE barcode ILIKE '%молоко%') ORDER BY (COALESCE(st.quantity, p.stock, 0) > 0) DESC, CASE WHEN starts_with(lower(p.title), 'молоко') THEN 0 WHEN position(' молоко' in lower(p.title)) > 0 THEN 1 WHEN position('молоко' in lower(p.title)) > 0 THEN 2 WHEN position('молоко' in lower(COALESCE(NULLIF(p.barcode, ''), p.sku, ''))) > 0 THEN 3 ELSE 4 END, lower(p.title) COLLATE "C" LIMIT 20 OFFSET 0;
\echo
\echo === C3: каталог сторінка 5 (OFFSET 80), total скалярним підзапитом ===
EXPLAIN (ANALYZE, TIMING OFF) SELECT p.id, p.title, (SELECT count(*) FROM products p LEFT JOIN stock st ON st.product_id = p.id AND st.store_id = '65d5db51-672f-4a38-9c1e-f36c5feb5374'::uuid) AS total_count FROM products p LEFT JOIN stock st ON st.product_id = p.id AND st.store_id = '65d5db51-672f-4a38-9c1e-f36c5feb5374'::uuid ORDER BY lower(p.title) COLLATE "C" LIMIT 20 OFFSET 80;
\echo
\echo === C4: короткий пошук (2 символи, trgm не застосовний) ===
EXPLAIN (ANALYZE, TIMING OFF) SELECT p.id, p.title, (SELECT count(*) FROM products p WHERE p.id IN (SELECT id FROM products WHERE title ILIKE '%мо%' UNION SELECT id FROM products WHERE barcode ILIKE '%мо%' UNION SELECT id FROM products WHERE sku ILIKE '%мо%' UNION SELECT product_id FROM barcodes WHERE barcode ILIKE '%мо%')) AS total_count FROM products p WHERE p.id IN (SELECT id FROM products WHERE title ILIKE '%мо%' UNION SELECT id FROM products WHERE barcode ILIKE '%мо%' UNION SELECT id FROM products WHERE sku ILIKE '%мо%' UNION SELECT product_id FROM barcodes WHERE barcode ILIKE '%мо%') ORDER BY lower(p.title) COLLATE "C" LIMIT 20;
