-- Вимір після індексу ix_products_title_lower_c (хаб).
SET plan_cache_mode = force_generic_plan;
\echo === K1: каталог, count як скалярний підзапит (ІНДЕКС Є) ===
EXPLAIN (ANALYZE, TIMING OFF) SELECT p.id, p.barcode, p.sku, p.title, p.description, COALESCE(NULLIF(st.price,0),p.price)::text AS price, p.cost_price::text, p.markup::text, COALESCE(st.quantity,p.stock)::text AS stock, p.recommended_qty::text, p.uktzed, p.scan_excise, p.tax_rate::text, p.tax_group, p.is_weight, p.unit, p.category_id, p.supplier_id, p.created_at, p.updated_at, (SELECT count(*) FROM products p LEFT JOIN stock st ON st.product_id = p.id AND st.store_id = '65d5db51-672f-4a38-9c1e-f36c5feb5374'::uuid) AS total_count FROM products p LEFT JOIN stock st ON st.product_id = p.id AND st.store_id = '65d5db51-672f-4a38-9c1e-f36c5feb5374'::uuid ORDER BY lower(p.title) COLLATE "C" LIMIT 20 OFFSET 0;
\echo
\echo === K0: каталог, поточний WindowAgg (ІНДЕКС Є) ===
EXPLAIN (ANALYZE, TIMING OFF) SELECT p.id, p.barcode, p.sku, p.title, p.description, COALESCE(NULLIF(st.price,0),p.price)::text AS price, p.cost_price::text, p.markup::text, COALESCE(st.quantity,p.stock)::text AS stock, p.recommended_qty::text, p.uktzed, p.scan_excise, p.tax_rate::text, p.tax_group, p.is_weight, p.unit, p.category_id, p.supplier_id, p.created_at, p.updated_at, count(*) OVER () AS total_count FROM products p LEFT JOIN stock st ON st.product_id = p.id AND st.store_id = '65d5db51-672f-4a38-9c1e-f36c5feb5374'::uuid ORDER BY lower(p.title) COLLATE "C" LIMIT 20 OFFSET 0;
\echo
\echo === S1: пошук молоко, count як скалярний підзапит ===
EXPLAIN (ANALYZE, TIMING OFF) SELECT p.id, p.title, (SELECT count(*) FROM products p WHERE (p.title ILIKE '%молоко%' OR p.barcode ILIKE '%молоко%' OR p.sku ILIKE '%молоко%' OR EXISTS (SELECT 1 FROM barcodes b WHERE b.product_id = p.id AND b.barcode ILIKE '%молоко%'))) AS total_count FROM products p LEFT JOIN stock st ON st.product_id = p.id AND st.store_id = '65d5db51-672f-4a38-9c1e-f36c5feb5374'::uuid WHERE (p.title ILIKE '%молоко%' OR p.barcode ILIKE '%молоко%' OR p.sku ILIKE '%молоко%' OR EXISTS (SELECT 1 FROM barcodes b WHERE b.product_id = p.id AND b.barcode ILIKE '%молоко%')) ORDER BY (COALESCE(st.quantity, p.stock, 0) > 0) DESC, CASE WHEN starts_with(lower(p.title), 'молоко') THEN 0 WHEN position(' молоко' in lower(p.title)) > 0 THEN 1 WHEN position('молоко' in lower(p.title)) > 0 THEN 2 WHEN position('молоко' in lower(COALESCE(NULLIF(p.barcode, ''), p.sku, ''))) > 0 THEN 3 ELSE 4 END, lower(p.title) COLLATE "C" LIMIT 20 OFFSET 0;
